name: Javadoc

on:
  push:
    branches: [ master ]

jobs:
  javadoc:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Javadocs with Gradle
      run: ./gradlew javadoc

    - name: Move javadoc to docs/
      run: mv build/docs/javadoc docs/

    - name: Checkout Git
      run: git checkout -b gh-pages

    - name: Remove everything from git
      run: git rm -rf --cached .github gradle src .gitignore *.gradle gradlew*

    - name: Set upstream branch
      run: git branch --set-upstream-to=origin/master gh-pages

    - uses: EndBug/add-and-commit@v7
      with:
        add: '["docs"]'
        author_name: TheDutchMC
        author_email: github@thedutchmc.nl
        branch: gh-pages
        message: 'Automated Javadoc'
        push: origin gh-pages -f
        signoff: true